import { createId } from "@src/pages/Editor/utils/ids";

import type { PageData } from "../types";
import { row } from "./helpers";

export const quickUpdate = (): PageData => ({
  title: "Quick update",
  backgroundColor: "#ffffff",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 96,
      paddingX: 96,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "FRIDAY, MAY 10",
            color: "#8a8a8a",
            fontSize: 12,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "A quick note from my desk —",
            level: 2,
            color: "#1a1a1a",
            fontSize: 22,
            fontWeight: 500,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            letterSpacing: 0,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Hi friend,",
            color: "#2a2a2a",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            lineHeight: 1.8,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "I wanted to write a short letter instead of the usual newsletter this week. No pictures, no buttons — just a few honest thoughts about what I have been working on.",
            color: "#2a2a2a",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            lineHeight: 1.8,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "The new project is taking longer than I expected, but that has turned out to be a gift. Slowing down has surfaced ideas that the deadline version of me would have steamrolled.",
            color: "#2a2a2a",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            lineHeight: 1.8,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "If you ever feel like writing back, I read everything. Just hit reply.",
            color: "#2a2a2a",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            lineHeight: 1.8,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Warmly,\nMira",
            color: "#2a2a2a",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            lineHeight: 1.8,
          },
          {
            id: createId("el"),
            type: "spacer",
            height: 24,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "SENT FROM A QUIET MORNING",
            color: "#8a8a8a",
            fontSize: 11,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.6,
          },
        ],
      ],
    }),
  ],
});
