import { createId } from "@src/pages/Editor/utils/ids";

import type { PageData } from "../types";
import { row } from "./helpers";

export const springNewsletter = (): PageData => ({
  title: "Spring newsletter",
  backgroundColor: "#ffffff",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 56,
      paddingX: 64,
      backgroundColor: "transparent",
      columnsCount: 2,
      columnWidths: [2, 1],
      columnGap: 24,
      columns: [
        [
          {
            id: createId("el"),
            type: "heading",
            text: "The Atelier",
            level: 2,
            color: "#1f1f1f",
            fontSize: 34,
            fontWeight: 600,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            letterSpacing: -0.5,
          },
        ],
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "ISSUE 14 · SPRING",
            color: "#6a6a6a",
            fontSize: 11,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "right",
            lineHeight: 1.6,
          },
        ],
      ],
    }),
    row({
      paddingY: 16,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "divider",
            color: "#1f1f1f",
            thickness: 2,
            widthPct: 100,
          },
        ],
      ],
    }),
    row({
      paddingY: 32,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "heading",
            text: "Slow mornings, small wins, and a studio update.",
            level: 2,
            color: "#1f1f1f",
            fontSize: 38,
            fontWeight: 500,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            letterSpacing: 0,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "A round-up of what we have been making, reading, and obsessing over this season.",
            color: "#404040",
            fontSize: 15,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.7,
          },
        ],
      ],
    }),
    row({
      paddingY: 32,
      paddingX: 64,
      backgroundColor: "transparent",
      columnsCount: 2,
      columnWidths: [1, 1],
      columnGap: 28,
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "STUDIO NOTES",
            color: "#a06d3a",
            fontSize: 10,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "A new collection in linen",
            level: 3,
            color: "#1f1f1f",
            fontSize: 18,
            fontWeight: 500,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            letterSpacing: 0,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Seven everyday pieces in undyed European linen, made in small runs to order.",
            color: "#555",
            fontSize: 13,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.65,
          },
        ],
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "READING",
            color: "#a06d3a",
            fontSize: 10,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "Three books on quiet",
            level: 3,
            color: "#1f1f1f",
            fontSize: 18,
            fontWeight: 500,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            letterSpacing: 0,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Slim volumes from our shelf to yours — for the in-between hours of the day.",
            color: "#555",
            fontSize: 13,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.65,
          },
        ],
      ],
    }),
    row({
      paddingY: 32,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "button",
            label: "Read the full issue",
            href: "",
            backgroundColor: "#1f1f1f",
            textColor: "#ffffff",
            paddingX: 32,
            paddingY: 16,
            radius: 0,
            fontSize: 12,
            align: "center",
            letterSpacing: 3,
          },
        ],
      ],
    }),
  ],
});
