import { createId } from "@src/pages/Editor/utils/ids";

import type { PageData } from "../types";
import { row } from "./helpers";

export const welcomeFamily = (): PageData => ({
  title: "Welcome to the family",
  backgroundColor: "#f4ede3",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 80,
      paddingX: 72,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "WELCOME",
            color: "#8a7665",
            fontSize: 13,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "center",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "Hello, lovely friend.",
            level: 1,
            color: "#2a201b",
            fontSize: 72,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            letterSpacing: -1,
          },
          {
            id: createId("el"),
            type: "divider",
            color: "#b8a896",
            thickness: 1,
            widthPct: 12,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "I'm so glad you're here. This little corner of the internet is where I share studio notes, slow living rituals, and the occasional recipe.",
            color: "#5a4a40",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            lineHeight: 1.85,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Pour yourself something warm and stay a while.",
            color: "#5a4a40",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            lineHeight: 1.85,
          },
          {
            id: createId("el"),
            type: "spacer",
            height: 24,
          },
          {
            id: createId("el"),
            type: "button",
            label: "Read the journal",
            href: "",
            backgroundColor: "transparent",
            textColor: "#3a2f29",
            paddingX: 40,
            paddingY: 16,
            radius: 0,
            fontSize: 12,
            align: "center",
            letterSpacing: 3,
          },
          {
            id: createId("el"),
            type: "spacer",
            height: 32,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "— with love, Mira",
            color: "#6a5648",
            fontSize: 18,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            lineHeight: 1.6,
          },
        ],
      ],
    }),
  ],
});
