import { createId } from "@src/pages/Editor/utils/ids";

import type { PageData, PageRow } from "./types";

const row = (config: Partial<PageRow> & Pick<PageRow, "columns">): PageRow => ({
  id: createId("row"),
  backgroundColor: "transparent",
  paddingX: 64,
  paddingY: 40,
  marginY: 0,
  columnsCount: 1,
  columnWidths: [1],
  columnGap: 24,
  ...config,
});

export const createEmptyPage = (): PageData => ({
  title: "Untitled page",
  backgroundColor: "#ffffff",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 96,
      columns: [
        [
          {
            id: createId("el"),
            type: "heading",
            text: "Build something beautiful",
            level: 1,
            color: "#1f1f1f",
            fontSize: 56,
            fontWeight: 600,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            letterSpacing: -1,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Drop elements from the menu on the left to start your page. Click any element to edit it on the right.",
            color: "#5a5a5a",
            fontSize: 18,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "center",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "button",
            label: "Get started",
            href: "#",
            backgroundColor: "#1f1f1f",
            textColor: "#ffffff",
            paddingX: 36,
            paddingY: 16,
            radius: 4,
            fontSize: 14,
            align: "center",
            letterSpacing: 1.5,
          },
        ],
      ],
    }),
  ],
});

const boldSale = (): PageData => ({
  title: "Bold sale announcement",
  backgroundColor: "#1a1411",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 96,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "BLACK FRIDAY",
            color: "#f4ece1",
            fontSize: 12,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.4,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "70% OFF",
            level: 1,
            color: "#f8c97a",
            fontSize: 132,
            fontWeight: 900,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            letterSpacing: -5,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Our biggest sale of the year. Everything in store is marked down through midnight Sunday.",
            color: "#f4ece1",
            fontSize: 17,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.7,
          },
          {
            id: createId("el"),
            type: "spacer",
            height: 24,
          },
          {
            id: createId("el"),
            type: "button",
            label: "Shop the sale",
            href: "#",
            backgroundColor: "#f8c97a",
            textColor: "#1a1411",
            paddingX: 36,
            paddingY: 18,
            radius: 0,
            fontSize: 13,
            align: "left",
            letterSpacing: 1.5,
          },
        ],
      ],
    }),
    row({
      paddingY: 24,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "Use code BLACK70 at checkout",
            color: "#a08c75",
            fontSize: 11,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.4,
          },
        ],
      ],
    }),
  ],
});

const welcomeFamily = (): PageData => ({
  title: "Welcome to the family",
  backgroundColor: "#f4ede3",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 80,
      paddingX: 72,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "WELCOME",
            color: "#8a7665",
            fontSize: 13,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "center",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "Hello, lovely friend.",
            level: 1,
            color: "#2a201b",
            fontSize: 72,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            letterSpacing: -1,
          },
          {
            id: createId("el"),
            type: "divider",
            color: "#b8a896",
            thickness: 1,
            widthPct: 12,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "I'm so glad you're here. This little corner of the internet is where I share studio notes, slow living rituals, and the occasional recipe.",
            color: "#5a4a40",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            lineHeight: 1.85,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Pour yourself something warm and stay a while.",
            color: "#5a4a40",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            lineHeight: 1.85,
          },
          {
            id: createId("el"),
            type: "spacer",
            height: 24,
          },
          {
            id: createId("el"),
            type: "button",
            label: "Read the journal",
            href: "#",
            backgroundColor: "transparent",
            textColor: "#3a2f29",
            paddingX: 40,
            paddingY: 16,
            radius: 0,
            fontSize: 12,
            align: "center",
            letterSpacing: 3,
          },
          {
            id: createId("el"),
            type: "spacer",
            height: 32,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "— with love, Mira",
            color: "#6a5648",
            fontSize: 18,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            lineHeight: 1.6,
          },
        ],
      ],
    }),
  ],
});

const springNewsletter = (): PageData => ({
  title: "Spring newsletter",
  backgroundColor: "#ffffff",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 56,
      paddingX: 64,
      backgroundColor: "transparent",
      columnsCount: 2,
      columnWidths: [2, 1],
      columnGap: 24,
      columns: [
        [
          {
            id: createId("el"),
            type: "heading",
            text: "The Atelier",
            level: 2,
            color: "#1f1f1f",
            fontSize: 34,
            fontWeight: 700,
            fontFamily: "Georgia, serif",
            align: "left",
            letterSpacing: -0.5,
          },
        ],
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "ISSUE 14 · SPRING",
            color: "#6a6a6a",
            fontSize: 11,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "right",
            lineHeight: 1.6,
          },
        ],
      ],
    }),
    row({
      paddingY: 16,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "divider",
            color: "#1f1f1f",
            thickness: 2,
            widthPct: 100,
          },
        ],
      ],
    }),
    row({
      paddingY: 32,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "heading",
            text: "Slow mornings, small wins, and a studio update.",
            level: 2,
            color: "#1f1f1f",
            fontSize: 38,
            fontWeight: 500,
            fontFamily: "Georgia, serif",
            align: "left",
            letterSpacing: 0,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "A round-up of what we have been making, reading, and obsessing over this season.",
            color: "#404040",
            fontSize: 15,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.7,
          },
        ],
      ],
    }),
    row({
      paddingY: 32,
      paddingX: 64,
      backgroundColor: "transparent",
      columnsCount: 2,
      columnWidths: [1, 1],
      columnGap: 28,
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "STUDIO NOTES",
            color: "#a06d3a",
            fontSize: 10,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "A new collection in linen",
            level: 3,
            color: "#1f1f1f",
            fontSize: 18,
            fontWeight: 500,
            fontFamily: "Georgia, serif",
            align: "left",
            letterSpacing: 0,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Seven everyday pieces in undyed European linen, made in small runs to order.",
            color: "#555",
            fontSize: 13,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.65,
          },
        ],
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "READING",
            color: "#a06d3a",
            fontSize: 10,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "Three books on quiet",
            level: 3,
            color: "#1f1f1f",
            fontSize: 18,
            fontWeight: 500,
            fontFamily: "Georgia, serif",
            align: "left",
            letterSpacing: 0,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Slim volumes from our shelf to yours — for the in-between hours of the day.",
            color: "#555",
            fontSize: 13,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.65,
          },
        ],
      ],
    }),
    row({
      paddingY: 32,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "button",
            label: "Read the full issue",
            href: "#",
            backgroundColor: "#1f1f1f",
            textColor: "#ffffff",
            paddingX: 32,
            paddingY: 16,
            radius: 0,
            fontSize: 12,
            align: "center",
            letterSpacing: 3,
          },
        ],
      ],
    }),
  ],
});

const thankYouNote = (): PageData => ({
  title: "Thank you note",
  backgroundColor: "#ece4d6",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 100,
      paddingX: 72,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "heading",
            text: "thank you",
            level: 1,
            color: "#2a201b",
            fontSize: 86,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            letterSpacing: -1.5,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "FOR BEING HERE",
            color: "#6a5849",
            fontSize: 13,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "center",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Your support means more than you know. Every order, message, and share helps keep this small studio going.",
            color: "#4a3d34",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "center",
            lineHeight: 1.85,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "As a little token, here is a code for 15% off your next order: STAY15",
            color: "#4a3d34",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "center",
            lineHeight: 1.85,
          },
          {
            id: createId("el"),
            type: "spacer",
            height: 32,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "with gratitude,",
            color: "#5a4838",
            fontSize: 22,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            lineHeight: 1.4,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "THE ATELIER TEAM",
            color: "#8a7665",
            fontSize: 11,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "center",
            lineHeight: 1.6,
          },
        ],
      ],
    }),
  ],
});

const findYourLight = (): PageData => ({
  title: "Find your light",
  backgroundColor: "#faf6ef",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 80,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "A MONDAY NOTE",
            color: "#a08c75",
            fontSize: 12,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.6,
          },
        ],
      ],
    }),
    row({
      paddingY: 24,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "quote",
            text: "Almost everything will work again if you unplug it for a few minutes — including you.",
            author: "Anne Lamott",
            color: "#2a241f",
            fontSize: 42,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
          },
        ],
      ],
    }),
    row({
      paddingY: 80,
      paddingX: 64,
      backgroundColor: "transparent",
      columnsCount: 2,
      columnWidths: [2, 1],
      columnGap: 24,
      columns: [
        [
          {
            id: createId("el"),
            type: "button",
            label: "Read this week",
            href: "#",
            backgroundColor: "transparent",
            textColor: "#2a241f",
            paddingX: 0,
            paddingY: 8,
            radius: 0,
            fontSize: 13,
            align: "left",
            letterSpacing: 3,
          },
        ],
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "NO. 042",
            color: "#b0a08c",
            fontSize: 11,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "right",
            lineHeight: 1.6,
          },
        ],
      ],
    }),
  ],
});

const quickUpdate = (): PageData => ({
  title: "Quick update",
  backgroundColor: "#ffffff",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 96,
      paddingX: 96,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "FRIDAY, MAY 10",
            color: "#8a8a8a",
            fontSize: 12,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "A quick note from my desk —",
            level: 2,
            color: "#1a1a1a",
            fontSize: 22,
            fontWeight: 500,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            letterSpacing: 0,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Hi friend,",
            color: "#2a2a2a",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            lineHeight: 1.8,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "I wanted to write a short letter instead of the usual newsletter this week. No pictures, no buttons — just a few honest thoughts about what I have been working on.",
            color: "#2a2a2a",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            lineHeight: 1.8,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "The new project is taking longer than I expected, but that has turned out to be a gift. Slowing down has surfaced ideas that the deadline version of me would have steamrolled.",
            color: "#2a2a2a",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            lineHeight: 1.8,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "If you ever feel like writing back, I read everything. Just hit reply.",
            color: "#2a2a2a",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            lineHeight: 1.8,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Warmly,\nMira",
            color: "#2a2a2a",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "left",
            lineHeight: 1.8,
          },
          {
            id: createId("el"),
            type: "spacer",
            height: 24,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "SENT FROM A QUIET MORNING",
            color: "#8a8a8a",
            fontSize: 11,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.6,
          },
        ],
      ],
    }),
  ],
});

const templateBuilders: Record<string, () => PageData> = {
  "bold-sale-announcement": boldSale,
  "welcome-to-the-family": welcomeFamily,
  "spring-newsletter": springNewsletter,
  "thank-you-note": thankYouNote,
  "find-your-light": findYourLight,
  "quick-update": quickUpdate,
};

export const buildPageForTemplate = (
  templateId: string | undefined
): PageData => {
  if (!templateId) return createEmptyPage();
  const builder = templateBuilders[templateId];
  if (builder) return builder();
  return createEmptyPage();
};
