import type { PageData, PageRow } from "./types";
import { createId } from "../utils/ids";

const row = (config: Partial<PageRow> & Pick<PageRow, "columns">): PageRow => ({
  id: createId("row"),
  backgroundColor: "transparent",
  paddingX: 64,
  paddingY: 40,
  marginY: 0,
  columnsCount: 1,
  columnWidths: [1],
  columnGap: 24,
  ...config,
});

export const createEmptyPage = (): PageData => ({
  title: "Untitled page",
  backgroundColor: "#ffffff",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 96,
      columns: [
        [
          {
            id: createId("el"),
            type: "heading",
            text: "Build something beautiful",
            level: 1,
            color: "#1f1f1f",
            fontSize: 56,
            fontWeight: 600,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            letterSpacing: -1,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Drop elements from the menu on the left to start your page. Click any element to edit it on the right.",
            color: "#5a5a5a",
            fontSize: 18,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "center",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "button",
            label: "Get started",
            href: "#",
            backgroundColor: "#1f1f1f",
            textColor: "#ffffff",
            paddingX: 36,
            paddingY: 16,
            radius: 4,
            fontSize: 14,
            align: "center",
            letterSpacing: 1.5,
          },
        ],
      ],
    }),
  ],
});

const boldSale = (): PageData => ({
  title: "Bold sale announcement",
  backgroundColor: "#1a1411",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 96,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "BLACK FRIDAY",
            color: "#f4ece1",
            fontSize: 12,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.4,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "70% OFF",
            level: 1,
            color: "#f8c97a",
            fontSize: 132,
            fontWeight: 900,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            letterSpacing: -5,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Our biggest sale of the year. Everything in store is marked down through midnight Sunday.",
            color: "#f4ece1",
            fontSize: 17,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.7,
          },
          {
            id: createId("el"),
            type: "spacer",
            height: 24,
          },
          {
            id: createId("el"),
            type: "button",
            label: "Shop the sale",
            href: "#",
            backgroundColor: "#f8c97a",
            textColor: "#1a1411",
            paddingX: 36,
            paddingY: 18,
            radius: 0,
            fontSize: 13,
            align: "left",
            letterSpacing: 1.5,
          },
        ],
      ],
    }),
    row({
      paddingY: 24,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "Use code BLACK70 at checkout",
            color: "#a08c75",
            fontSize: 11,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.4,
          },
        ],
      ],
    }),
  ],
});

const welcomeFamily = (): PageData => ({
  title: "Welcome to the family",
  backgroundColor: "#f4ede3",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 80,
      paddingX: 72,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "WELCOME",
            color: "#8a7665",
            fontSize: 13,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "center",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "Hello, lovely friend.",
            level: 1,
            color: "#2a201b",
            fontSize: 72,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            letterSpacing: -1,
          },
          {
            id: createId("el"),
            type: "divider",
            color: "#b8a896",
            thickness: 1,
            widthPct: 12,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "I'm so glad you're here. This little corner of the internet is where I share studio notes, slow living rituals, and the occasional recipe.",
            color: "#5a4a40",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            lineHeight: 1.85,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Pour yourself something warm and stay a while.",
            color: "#5a4a40",
            fontSize: 16,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            lineHeight: 1.85,
          },
          {
            id: createId("el"),
            type: "spacer",
            height: 24,
          },
          {
            id: createId("el"),
            type: "button",
            label: "Read the journal",
            href: "#",
            backgroundColor: "transparent",
            textColor: "#3a2f29",
            paddingX: 40,
            paddingY: 16,
            radius: 0,
            fontSize: 12,
            align: "center",
            letterSpacing: 3,
          },
          {
            id: createId("el"),
            type: "spacer",
            height: 32,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "— with love, Mira",
            color: "#6a5648",
            fontSize: 18,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            align: "center",
            lineHeight: 1.6,
          },
        ],
      ],
    }),
  ],
});

const springNewsletter = (): PageData => ({
  title: "Spring newsletter",
  backgroundColor: "#ffffff",
  paddingX: 0,
  paddingY: 0,
  rows: [
    row({
      paddingY: 56,
      paddingX: 64,
      backgroundColor: "transparent",
      columnsCount: 2,
      columnWidths: [2, 1],
      columnGap: 24,
      columns: [
        [
          {
            id: createId("el"),
            type: "heading",
            text: "The Atelier",
            level: 2,
            color: "#1f1f1f",
            fontSize: 34,
            fontWeight: 700,
            fontFamily: "Georgia, serif",
            align: "left",
            letterSpacing: -0.5,
          },
        ],
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "ISSUE 14 · SPRING",
            color: "#6a6a6a",
            fontSize: 11,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "right",
            lineHeight: 1.6,
          },
        ],
      ],
    }),
    row({
      paddingY: 16,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "divider",
            color: "#1f1f1f",
            thickness: 2,
            widthPct: 100,
          },
        ],
      ],
    }),
    row({
      paddingY: 32,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "heading",
            text: "Slow mornings, small wins, and a studio update.",
            level: 2,
            color: "#1f1f1f",
            fontSize: 38,
            fontWeight: 500,
            fontFamily: "Georgia, serif",
            align: "left",
            letterSpacing: 0,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "A round-up of what we have been making, reading, and obsessing over this season.",
            color: "#404040",
            fontSize: 15,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.7,
          },
        ],
      ],
    }),
    row({
      paddingY: 32,
      paddingX: 64,
      backgroundColor: "transparent",
      columnsCount: 2,
      columnWidths: [1, 1],
      columnGap: 28,
      columns: [
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "STUDIO NOTES",
            color: "#a06d3a",
            fontSize: 10,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "A new collection in linen",
            level: 3,
            color: "#1f1f1f",
            fontSize: 18,
            fontWeight: 500,
            fontFamily: "Georgia, serif",
            align: "left",
            letterSpacing: 0,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Seven everyday pieces in undyed European linen, made in small runs to order.",
            color: "#555",
            fontSize: 13,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.65,
          },
        ],
        [
          {
            id: createId("el"),
            type: "paragraph",
            text: "READING",
            color: "#a06d3a",
            fontSize: 10,
            fontWeight: 500,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.6,
          },
          {
            id: createId("el"),
            type: "heading",
            text: "Three books on quiet",
            level: 3,
            color: "#1f1f1f",
            fontSize: 18,
            fontWeight: 500,
            fontFamily: "Georgia, serif",
            align: "left",
            letterSpacing: 0,
          },
          {
            id: createId("el"),
            type: "paragraph",
            text: "Slim volumes from our shelf to yours — for the in-between hours of the day.",
            color: "#555",
            fontSize: 13,
            fontWeight: 400,
            fontFamily: "'Helvetica Neue', Arial, sans-serif",
            align: "left",
            lineHeight: 1.65,
          },
        ],
      ],
    }),
    row({
      paddingY: 32,
      paddingX: 64,
      backgroundColor: "transparent",
      columns: [
        [
          {
            id: createId("el"),
            type: "button",
            label: "Read the full issue",
            href: "#",
            backgroundColor: "#1f1f1f",
            textColor: "#ffffff",
            paddingX: 32,
            paddingY: 16,
            radius: 0,
            fontSize: 12,
            align: "center",
            letterSpacing: 3,
          },
        ],
      ],
    }),
  ],
});

const templateBuilders: Record<string, () => PageData> = {
  "bold-sale-announcement": boldSale,
  "welcome-to-the-family": welcomeFamily,
  "spring-newsletter": springNewsletter,
};

export const buildPageForTemplate = (templateId: string | undefined): PageData => {
  if (!templateId) return createEmptyPage();
  const builder = templateBuilders[templateId];
  if (builder) return builder();
  return createEmptyPage();
};
